### ISSUE TITLE
Can't enable auto-merge for this pull request

### ISSUE THREAD

**Issue by bennycode** [dependabot/fetch-metadata#172]
I am using "dependabot/fetch-metadata" v1.2.1 but I am often receiving an error message that it cannot automatically merge PRs:

**Enable auto-merge for Dependabot PRs**

```
Run gh pr merge --auto --squash "$PR_URL"
Message: Can't enable auto-merge for this pull request., Locations: [{Line:[1](https://github.com/southpolecarbon/alaska/runs/5287794531#step:3:1) Column:[7](https://github.com/southpolecarbon/alaska/runs/5287794531#step:3:7)2}]
Error: Process completed with exit code 1.
```

Am I missing something in my workflow to make it work?

```yml
name: Dependabot auto-merge
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by mwaddell** [comment]
@bennycode - your action isn't actually using `fetch-metadata` (it's ignoring the output) - so it's equivalent to:

```yaml
name: Dependabot auto-merge
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The error you're getting is being thrown by the github cli.  I see you already posted about this https://github.com/cli/cli/discussions/3660 - if you got an answer on how we can update our example workflow to address this issue, please let me know.

**Comment by westonruter** [comment]
@bennycode Did you resolve this issue? I am facing the same. In my repo, I have branch protection enabled with:

1. Require approvals
2. Require status checks to pass before merging
3. Restrict who can push to matching branches

My latest attempt (https://github.com/ampproject/amp-wp/pull/6975) is to wait to run `gh pr merge --auto` until _after_ all of the checks have passed but _before_ I run `gh pr review --approve`. Not sure yet if it works.

**Comment by mwaddell** [comment]
@bennycode Does using a personal access token solve the issue?

**Comment by bennycode** [comment]
I added a personal access token but I am still seeing this error:

> gh pr merge --auto --squash "$PR_URL"
  shell: /usr/bin/bash -e {0}
  env:
    PR_URL: ***
    GITHUB_TOKEN: ***
Message: Can't enable auto-merge for this pull request., Locations: [{Line:1 Column:[7](https://github.com/southpolecarbon/alaska/runs/5647485446?check_suite_focus=true#step:3:7)2}]
Error: Process completed with exit code 1.

I got it working in my personal public repository ([implementation](https://github.com/bennycode/ts-node-starter/blob/main/.github/workflows/merge-dependencies.yml), [proof that it works](https://github.com/bennycode/ts-node-starter/pull/472)) but it doesn't work in my org's private repository (that uses the same YML config and has a personal access token configured in GitHub Secrets). 😢

**Comment by bennycode** [comment]
**Phew!** I just found the issue. I ran into the "Can't enable auto-merge for this pull request" problem because [auto-merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request#about-auto-merge) wasn't activated in my repo. After activating the "**Allow auto-merge**" feature in my **repository settings** it worked:

![image](https://user-images.githubusercontent.com/469989/160016817-7b77f9a7-1d8f-4c0c-9585-3a198331ff3e.png)

This made the GitHub Actions bot do the following:

![image](https://user-images.githubusercontent.com/469989/160016884-bad53241-4a71-4001-807b-65a5b346859b.png)

Here is my final config:

```yml
name: Dependabot auto-merge

on: [pull_request_target]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge on PR
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

```

It actually works without "dependabot/fetch-metadata". I thought I needed "dependabot/fetch-metadata" because it was [listed here](https://github.com/dependabot/fetch-metadata/tree/v1.3.0#enabling-auto-merge). I also didn't knew that the [secrets.GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret) is something very special and not just a secret that you setup yourself in the "Action secrets" section of your repository settings.

Thanks to everyone who has helped!!

@brrygrdn: Can the "Can't enable auto-merge for this pull request" error message be improved in [GitHub's cli](https://cli.github.com/) to give a hint that auto-merge must be enabled on repository-level?
