### ISSUE TITLE
package-ecosystem metadata not outputting

### ISSUE THREAD

**Issue by hnandiwada** [dependabot/fetch-metadata#310]
I want dependabot PRs to automerge ONLY if the PR is to package.json. I have the following `ci.yml`. 
```
jobs:
  npm-automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Merge without testing for dependabot npm PRs
        id: merge
        if: ${{ steps.metadata.outputs.package-ecosystem == 'npm' }}
        run: |
          echo "detected npm ecosystem"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Fail if not npm
        id: fail-not-npm
        if: ${{ steps.metadata.outputs.package-ecosystem != 'npm' }}
        run: |
          exit 1
```
Dependabot recently created a PR to upgrade a dependency in our package.json. The first step ran, the second step was skipped, and the third step ran and exited 1. I _think_ this is a bug in the outputting of the `metadata` step. Either way, how can I get this to merge and pass?
