### ISSUE TITLE
Error: github-token is not set! Please add 'github-token: "${{ secrets.GITHUB_TOKEN }}"' to your workflow file.

### ISSUE THREAD

**Issue by crazyoptimist** [dependabot/fetch-metadata#426]
Our workflow file for auto-merging dependabot PR is below:
```yaml
name: Auto-Merge Dependabot PR
on:
  pull_request:
    branches: ['development']

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: '${{ secrets.DEPENDABOT_GITHUB_TOKEN }}'

      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_GITHUB_TOKEN }}

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.DEPENDABOT_GITHUB_TOKEN}}
```
We use the same workflow in a dozen of repos, and it works well.
But, we see below error in only two repos, even though there's no difference in the workflow file(just copy-pasted), and the `DEPENDABOT_GITHUB_TOKEN` is an org secret.

```bash
Run dependabot/fetch-metadata@v1
  with:
    skip-commit-verification: false
    skip-verification: false
Error: github-token is not set! Please add 'github-token: "${{ secrets.GITHUB_TOKEN }}"' to your workflow file.
```

How can it be possible, and what could be the root cause?

EDIT: As I tried to set this up in more repos, the same thing happens even after a few successful auto-merges. So it works and then stops to work showing the above error with no clue. No changes applied to the workflow or anything else in the repo.
