### ISSUE TITLE
`fetch-metadata` can not fetch metadata when using `workflow_run` event

### ISSUE THREAD

**Issue by kimnh-0823** [dependabot/fetch-metadata#490]
### Errror

I'm using mono-repository for a microservices:
- Dependabot opens PR for Microservice 1 (Ex: path: /src/microservices-1/*)
- The workflow `CI for Microservice 1` is triggered.
- The workflow `Dependabot` is triggered after `CI for Microservice 1` passed
- The workflow `Dependabot` display error.

![image](https://github.com/dependabot/fetch-metadata/assets/49636247/af8dd107-3906-4d31-b4ef-5527c8d36e36)

It says:

```bash
Warning: Event payload missing `pull_request` key. Make sure you're triggering this action on the `pull_request` or `pull_request_target` events.
Error: PR is not from Dependabot, nothing to do.
```

### Expect

The workflow `Dependabot` can fetch metadata in this case.

### My workflow 

```yaml
name: Dependabot
on:
  workflow_run:
    workflows:
      - CI for Microservice 1
      - CI for Microservice 2
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: |-
      github.actor == 'dependabot[bot]' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-approve non-major updates
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge non-major updates
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
