### ISSUE TITLE
Directory name is not properly extracted from branch name when using `-` separator.

### ISSUE THREAD

**Issue by dreid** [dependabot/fetch-metadata#493]
Given a branch name like `dependabot-pip-dirname-stripe-8.1.0` 
fetch-metadata produces metadata like:

```
  outputs.dependency-names: stripe
  outputs.dependency-type: direct:production
  outputs.update-type: version-update:semver-major
  outputs.directory: /dirname-stripe
  outputs.package-ecosystem: pip
  outputs.target-branch: trunk
  outputs.previous-version: 3.5.0
  outputs.new-version: 8.1.0
  outputs.compatibility-score: 0
  outputs.maintainer-changes: false
  outputs.dependency-group: 
  outputs.alert-state: 
  outputs.ghsa-id: 
  outputs.cvss: 0
```

The directory of `/dirname-stripe` is obviously incorrect the correct directory should be `/dirname`
