### ISSUE TITLE
github actor is not dependabot when rerunning the job

### ISSUE THREAD

**Issue by GersonTf** [dependabot/fetch-metadata#498]
I have an automerge workflow that checks the PR author:
`        if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]' }}
`
and gets triggered after the tests workflow:
```
name: Automerge Dependabot PRs
on:
  workflow_run:
    workflows: ["Lint and Test"]
    types:
      - completed
```

The problem is that, sometimes, if the tests fail, the dependabot automerge doesn't get triggered (as expected) and the PR stays open. When I fix the test issue, I re-run the jobs and the dependabot one doesn't get triggered anymore saying that the author is not dependabot when it is.
