### ISSUE TITLE
Dependabot "update-type" not available in metadata retrieved for PR using dependabot/fetch-metadata@v1

### ISSUE THREAD

**Issue by simonschaufi** [dependabot/fetch-metadata#499]
Hello, I have the same issue like this person: [Dependabot "update-type" not available in metadata retrieved for PR using dependabot/fetch-metadata@v1](https://stackoverflow.com/questions/77911994/dependabot-update-type-not-available-in-metadata-retrieved-for-pr-using-depend)

For example here: https://github.com/simonschaufi/php-libkml/actions/runs/8285139412/job/22672206081

```
Run dependabot/fetch-metadata@v1.6.0
  with:
    github-token: ***
    skip-commit-verification: false
    skip-verification: false
Parsing Dependabot metadata
Outputting metadata for 1 updated dependency
  outputs.dependency-names: rector/rector
  outputs.dependency-type: direct:development
  outputs.update-type: null
  outputs.directory: /
  outputs.package-ecosystem: composer
  outputs.target-branch: main
  outputs.previous-version: 
  outputs.new-version: 
  outputs.compatibility-score: 0
  outputs.maintainer-changes: false
  outputs.dependency-group: 
  outputs.alert-state: 
  outputs.ghsa-id: 
  outputs.cvss: 0
```

As you can see, `outputs.update-type` is always `null`

This is my workflow: https://github.com/simonschaufi/php-libkml/blob/main/.github/workflows/dependabot-auto-merge.yml

Is there some misconfiguration or is this really a bug?

**Comment by simonschaufi** [comment]
Similar but not the same: #339. On that bug report it's about the `v` prefix but in my case there is a simple version bump without the v prefix.

**Comment by simonschaufi** [comment]
@Nishnha could you give me some information about this issue?

**Comment by Century-ss** [comment]
@simonschaufi 
It seems that `update-type` is generated from the version information in the commit message as shown below.
However, there are cases where the version information is not included in the commit message, in which case `update-type` becomes null.

https://github.com/dependabot/fetch-metadata/blob/325b863556700e5e4d4ec23381993ef460dd8379/src/dependabot/update_metadata.ts#L58-L82

In [the above example](https://github.com/dependabot/fetch-metadata/issues/499#issue-2187293989), the commit message was as follows.
```
Updates the requirements on [rector/rector](https://github.com/rectorphp/rector) to permit the latest version.
- [Release notes](https://github.com/rectorphp/rector/releases)
- [Commits](rectorphp/rector@1.0.2...1.0.3)

---
updated-dependencies:
- dependency-name: rector/rector
  dependency-type: direct:development
...

Signed-off-by: dependabot[bot] <support@github.com>
```

There are two possible solutions.
1, Get the version information from somewhere other than the commit message (such as the title of the PR).
2, Modify the commit message so that the version information is always included (probably needs to be modified in other repositories).

@Nishnha 
I could not decide which option is better and would appreciate your opinion.
This also occurs in the latest v2 as well as v1.

**Comment by simonschaufi** [comment]
I think option 1 is the easier and better solution here.

**Comment by Nishnha** [comment]
Hi are these PRs that address a security update? We don't include the update-type for security updates at the moment.

**Comment by jeffwidman** [comment]
To add more context, so far we've purposefully avoided exposing `update-type` as we don't want to advertise that the repo getting the PR might have an open vulnerability.

I realize security by obscurity isn't great, and technically someone could figure this out themselves by cross-referencing CVE data with library versions... but still, let's not make the bad guys job easier.

One idea we've considered is that the risk is much lower for innersource/private repos, so we could optionally expose it for them. But suddenly this gets a bit more complicated and requiring more engineering time and so far it's not that frequently requested by users. So I don't expect us to actually spend any time on this anytime soon.

**Comment by timbru31** [comment]
> Hi are these PRs that address a security update? We don't include the update-type for security updates at the moment.

Nope. We are seeing it for regular dependency updates, too.
Interestingly only for those who `Updates the requirements on X to permit the latest version.` and not the `Bumps x from y to z.`

<img width="1290" alt="Screenshot 2024-09-02 at 12 35 33" src="https://github.com/user-attachments/assets/4d15030c-676b-4580-8fd8-132b8ad3799b">

**Comment by SalimBensiali** [comment]
This used to work and just seeing that update-type is set to null after I enabled group security updates.
@simonschaufi could this also be your case? There is an [existing issue](https://github.com/dependabot/dependabot-core/issues/4893#issuecomment-1739804088)

**Comment by rdohms** [comment]
We are seeing the same with an update with:
Commit: `[chore(deps): update hashicorp/aws requirement from ~> 5.80.0 to ~> 5.82.2]`
PR Title: `chore(deps): update hashicorp/aws requirement from ~> 5.80.0 to ~> 5.82.2 in /terraform/test/region/us-west-2`

**Comment by wzhao-eg** [comment]
We are facing a similar issue:
https://patch-diff.githubusercontent.com/raw/.../pull/674.patch
```
From a966a5b07dfd05c81ef6d59a79245e95b1e4342a Mon Sep 17 00:00:00 2001
From: "dependabot[bot]" <49699333+dependabot[bot]@users.noreply.github.com>
Date: Fri, 31 Jan 2025 17:11:50 +0000
Subject: [PATCH] Update faker requirement from ~=35.0 to ~=35.2 in /asset_api

Updates the requirements on [faker](https://github.com/joke2k/faker) to permit the latest version.
- [Release notes](https://github.com/joke2k/faker/releases)
- [Changelog](https://github.com/joke2k/faker/blob/master/CHANGELOG.md)
- [Commits](https://github.com/joke2k/faker/compare/v35.0.0...v35.2.0)

---
updated-dependencies:
- dependency-name: faker
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>
---
 asset_api/requirements.txt | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/asset_api/requirements.txt b/asset_api/requirements.txt
index 96d6f874..5c3b712b 100644
--- a/asset_api/requirements.txt
+++ b/asset_api/requirements.txt
@@ -13,7 +13,7 @@ deepdiff~=8.1
 beautifulsoup4~=4.12
 behave~=1.2
 pytest~=8.3
-faker~=35.0
+faker~=35.2
 httpx~=0.28
 black~=24.10
 coverage~=7.6
```

Dependabot metadata:
```
Run dependabot/fetch-metadata@v2.3.0
Parsing Dependabot metadata
Outputting metadata for [1](https://github.com/.../actions/runs/13077456100/job/36493020282#step:2:1) updated dependency
  outputs.dependency-names: faker
  outputs.dependency-type: direct:production
  outputs.update-type: null
  outputs.directory: /asset_api/master
  outputs.package-ecosystem: pip
  outputs.target-branch: master
  outputs.previous-version: 
  outputs.new-version: 
  outputs.compatibility-score: 0
  outputs.maintainer-changes: false
  outputs.dependency-group: 
  outputs.alert-state: 
  outputs.ghsa-id: 
  outputs.cvss: 0
```

How do we fix it?

Thank you!
